### ISSUE TITLE
Error running on Android project

### ISSUE THREAD

**Issue by sschuberth** [jakeouellette/inspector#23]
Running this on the `assemble` task of a fairly large Android project gives

	kotlin.TypeCastException: com.jakeout.gradle.inspector.InspectorPlugin! cannot be cast to com.jakeout.gradle.inspector.InspectorPlugin
		at com.jakeout.gradle.inspector.InspectorGradleListener.buildFinished(InspectorGradleListener.kt:157)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
		at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:249)
		at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:229)
		at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
		at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:221)
		at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:209)
		at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
		at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
		at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
		at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
		at com.sun.proxy.$Proxy9.buildFinished(Unknown Source)
		at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:108)
		at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
		at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
		at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
		at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
		at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
		at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
		at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
		at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
		at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
		at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
		at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
		at org.gradle.util.Swapper.swap(Swapper.java:38)
		at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
		at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
		at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
		at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
		at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
		at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
		at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)

Are Android projects supported yet?

**Comment by jakeouellette** [comment]
They definitely are, can you give me some of your debug log or OS information?e.g., jvm version? (I know, we were chatting email about windows, but that shouldn't cause this error.)

Any luke running the one from the plug in repository?

**Comment by sschuberth** [comment]
I'm using Windows 8.1 64-bit, Java 1.7.0_75 64-bit, Gradle 2.6, and Android Gradle plugin 1.3.1. Let me know what else you need.

**Comment by jdrider** [comment]
I see the same error with the following setup.  I have the Inspector plugin installed from the plugin repository.
```
Windows 8.1 x64
Java 1.8.0_60
Gradle 2.6
Android Plugin 1.4.0-beta1
```

**Comment by sschuberth** [comment]
BTW, I'm also getting the same on Ubuntu 15.04 64-bit, so it's not Windows specific.

**Comment by jakeouellette** [comment]
I'm doing some testing, so the code in question is this:

                val plugin = subProj.getPlugins().findPlugin(javaClass<InspectorPlugin>()) as InspectorPlugin
                val listener = plugin.listener
                if (listener != null) {
                    subprojectsByFile.put(subProj.getName(), listener.getIndex())
                }

Is it possible that the configuration for the subproject is different than the main project (E.g., different versions?) I'll look into constraining this loose type class a little bit to avoid trying to convert inexactly matching InspectorPlugin instances, but I'm still confused as to what might be causing this...

**Comment by jakeouellette** [comment]
Would it be possible to zip up a relatively trim test project that contains this issue, reproducibly? I'd definitely try to run it. That way any fix I attempt can be validated against your example. :)

**Comment by sschuberth** [comment]
While trying to come up with a minimal example, what does the `!` at the end of `com.jakeout.gradle.inspector.InspectorPlugin!` tell us (sorry, I don't know Kotlin at all)? Except that exclamation mark the classes from / to cast have the same name.

**Comment by jdrider** [comment]
@jakeouellette As far as a test project goes, I'm seeing this error on a newly generated project with Android Studio 1.4 Beta 3.  Nothing was added except for the Inspector plugin.

**Comment by jakeouellette** [comment]
Ah, now that's very interesting. Perhaps this has something to do with classpath isolation provided by the new plugin syntax? I'm not sure yet, but that's super helpfull @jdrider !

**Comment by jakeouellette** [comment]
I have a possible fix for this. Preparing a release.

**Comment by jakeouellette** [comment]
Just pushed a new version. @sschuberth could you confirm if this changes the behavior for you WRT this issue?

**Comment by sschuberth** [comment]
@jakeouellette I can confirm that building the current version from source and using it fixes the exception. Thanks a lot!
